base_url = "https://aleloprete.it"
title = "Alessandro Lo Prete"
description = "Threat Detection Engineer"
default_language = "en"
compile_sass = true
generate_feeds = true
feed_filenames = ["rss.xml"]
minify_html = false

taxonomies = [
    {name = "tags", feed = true},
]

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"
smart_punctuation = true

[extra]
author = "Alessandro Lo Prete"
subtitle = "Threat Detection Engineer · Sysdig Threat Research Team"
github = "https://github.com/aleLoPrete"
linkedin = "https://linkedin.com/in/alessandroloprete"
